source 'https://rubygems.org'

gem 'activesupport', '4.2.4'
gem 'rake', '10.4.2', require: false

group :production, :development, :test, :'acceptance-test' do
  gem 'rack', '1.6.4'
  gem 'grape', '0.13.0'
end

group :development do
  gem 'awesome_print', '1.2.0'
  gem 'byebug', '3.5.1'
end

group :test do
  gem 'rspec', '3.1.0'
  gem 'rack-test', '0.6.3', require: 'rack/test'
  gem 'simplecov', '0.9.1', require: false
end
